version: '3.8'

services:
  website:
    build: .
    container_name: outeniqua-website
    ports:
      - "8090:80"
    restart: unless-stopped
    networks:
      - outeniqua-network

  backend:
    build: ./backend
    container_name: outeniqua-backend
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - outeniqua-network

networks:
  outeniqua-network:
    driver: bridge 